### ISSUE TITLE
Add abstraction layer for running quadstore in a separate thread

### ISSUE THREAD

**Issue by jacoscaz** [jacoscaz/quadstore#146]
In some cases, quadstore would be better off running in a separate thread due to the in-memory query evaluation nature of Comunica which often becomes blocking to other aspects of the host application. Note that this is bound to become less of an issue with #115 , although still worth looking into.

**Comment by rubensworks** [comment]
Slightly related to https://github.com/comunica/comunica/issues/157

**Comment by jacoscaz** [comment]
Closing as interested parties use entirely different ways to achieve this and I wasn't able to find one that would be compatible with all use cases.
