### ISSUE TITLE
Replace `@types/rdf-js` with `@rdfjs/types`

### ISSUE THREAD

**Issue by jeswr** [jacoscaz/quadstore#167]
`@types/rdf-js` in https://github.com/jacoscaz/quadstore/blob/6e33be85f51230a15128cff61aaa67b0bde265b8/package.json#L76 should be `@rdfjs/types` instead. See https://github.com/rdfjs/types?tab=readme-ov-file#what-about-typesrdf-js

**Comment by jeswr** [comment]
Impressive turnaround @jacoscaz !

**Comment by jacoscaz** [comment]
I was just about to respond @jeswr - lucky coincidence that I was already working on quadstore :)

Thanks for flagging this! I'm making sure that other packages like `quadstore-comunica` are up to date with this. May I ask you how you came to notice this? Are you using quadstore?

**Comment by jeswr** [comment]
> May I ask you how you came to notice this? Are you using quadstore?

I was trying to pin down some warnings that I was getting from components.js building the Community Solid Server so I ran the following search to see what uses of `@types/rdf-js` were still in use

https://github.com/search?q=%22%5C%22%40types%2Frdf-js%5C%22%3A+%5C%22%22+language%3AJSON&type=code

**Comment by jacoscaz** [comment]
Cool stuff! Thanks again @jeswr , this is now on NPM in `quadstore@13.0.1` (and `quadstore-comunica@4.0.1`).
