### ISSUE TITLE
Question: Extracting a DatasetCore<Quad, Quad> from Quadstore

### ISSUE THREAD

**Issue by MMesch** [jacoscaz/quadstore#171]
Thanks for writing this nice library.

I am quite new to the RDFJS world and trying to use Quadstore for a SHACL validation use case in combination with the [rdf-validate-shacl](https://github.com/zazuko/rdf-validate-shacl) library that expects Quads to be passed as a DatasetCore data type. From the documentation it seems to me Quadstore is not implementing that interface, although most functions seem to be there?

I currently tried  something like

```
	async validateSHACL(shapes: DatasetCore) {
		const validator = new SHACLValidator(shapes, { factory: rdf });
		const allQuadsStream = await this.engine.queryQuads("CONSTRUCT WHERE {?s ?p ?o}");
		return await validator.validate(allQuadsStream);
```

This fails, as one would expect, with 

```
Argument of type 'ResultStream<Quad>' is not assignable to parameter of type 'DatasetCore<Quad, Quad>'.
```

Any hints on how to best use these together?

**Comment by jacoscaz** [comment]
Hello @MMesch,

Thank you for your kind words! I am happy to admit I'm not as familiar with the `Dataset` RDF/JS interfaces but, insofar as I remember, the main difference is that the interfaces implemented by Quadstore (`Source`, `Sink`, `Store`) are asynchronous (event emitters, streams, promises) whilst `Dataset` interfaces are synchronous. As such there's no straightforward way for Quadstore to implement `Dataset` interfaces as the former is inherently asynchronous.

Bridging between the two therefore means getting quads out of Quadstore and into a `Dataset` or `DatasetCore` instance:

```typescript
const { items: quads } = await store.get({});
let dataset = new DatasetCore();
for (quad of quads) {
  dataset = dataset.add(quad);
}
```

Or, if we use the `Dataset` interface:

```typescript
const { items: quads } = await store.get({});
const dataset = new Dataset().addAll(quads);
```

(I'm not in a position to test these snippets right now. If you find yourself struggling let me know and I'll have a deeper look.)

**Comment by jacoscaz** [comment]
@MMesch feel free to reopen if you need any further help!

**Comment by MMesch** [comment]
Thanks for your prompt reply. For now it's all good, I managed to solve it along the lines you described!
